### ISSUE TITLE
Extreme network usage by the tank under certain conditions?

### ISSUE THREAD

**Issue by ZeekDaGeek** [Drayshak/EnderTech#36]
Mod Version: endertech-1.7.10-0.3.0.364.jar
Forge Version: 1.7.10-10.13.2.1277
Other mods: https://docs.google.com/a/graythought.com/spreadsheet/ccc?key=0AndvSyXha_pPdHRYTXVtNVpHSzhrNjZxTDAzS2V3UEE&usp=sharing#gid=0

Something about EnderTech is updating tanks is very inefficient in terms of network resources and brings my internet connection to it's knees.

Here's my setup: http://zeekdageek.tv/ss/THRcD.jpg
He's the baseline upload/download/total that Minecraft uses: http://zeekdageek.tv/ss/9GhIQ.png

As soon as I assemble the tanks and start the refining it increases more than 10x.

http://zeekdageek.tv/ss/zjVRs.png

For comparison in Chrome I'm watching a 720p video from YouTube.

Both tanks have constant power being supplied

The rightmost tank has oil that is constantly being pulled out into the refineries in the center.
The left tank accepts the fuel and then exports it directly into Dynamos.

I had this exact setup using Resonant tanks and I didn't have any lag issues, only started when I added Ender Tanks.

I've seen it peak the download at 1,000,000 B/s before it just timed me out.

What information are the tanks sending back and forth?

**Comment by Drayshak** [comment]
I did try to pay attention to resource usage when writing it - it could be an interaction with another mod, or just a derp that's somehow gone unnoticed by everyone until now.

It should just invalidate the controller once a second, to force a visual update.

The images you included aren't working for me at the moment.

**Comment by Drayshak** [comment]
Does the extreme usage start when you assemble the tank alone, or specifically when you assemble the tank, and begin refining?

**Comment by Drayshak** [comment]
As a sanity check I assembled a tank on FC, did some normal stuff with it, even made a loop which Nullified fluids, and network usage was ~16 KB/s (which includes everything else in my main base). I'll take a look at the images you've included when they reappear and try to reproduce that way.

**Comment by ZeekDaGeek** [comment]
The images should be working now, I'm going to go ahead and make another test and document it a little better.

**Comment by ZeekDaGeek** [comment]
The experiment:

Two max sized Ender Tanks. Configs have been doubled to incentivize the usage of EnderTanks seeing as they require power.
http://zeekdageek.tv/ss/jfp70.png

Powered in the back using Capacitor banks, hooked up using EnderIO cables:
http://zeekdageek.tv/ss/PkGPf.png

In order to ensure that the tanks are filling and emptying at different rates the input and outputs of the tanks are going to be different.

The exchange between the two tanks is done at 800mb/t using EnderIO
http://zeekdageek.tv/ss/2ljpU.png

The left tank is emptied at 200mb/t:
http://zeekdageek.tv/ss/CMOcA.png

The right tank is filled using Gany's Surface Infinite water sources, multiple as needed:
http://zeekdageek.tv/ss/3VNER.png

**Comment by Drayshak** [comment]
We investigated a little more, and this seems to be a BuildCraft issue: http://i.imgur.com/Ta1qAXK.png
