### ISSUE TITLE
Client Crash when craft resonat charge pad

### ISSUE THREAD

**Issue by aik88** [Drayshak/EnderTech#38]
Client Crash when craft resonat charge pad

crashlog 1: Craft in Tinker's Crafting Table http://pastebin.com/H3iu4Hv3
crashlog 2: Craft in Vanilla Craft Table http://pastebin.com/8mwPH9GS

Item Pics show not correct (Recipe & NEI)
![2015-03-14_16 26 22](https://cloud.githubusercontent.com/assets/7645483/6652201/a693f10c-ca67-11e4-925e-98de37e006d3.png)

FORGE: 10.13.2.1307
MOD List: http://pastebin.com/dpe1AmeS

**Comment by Drayshak** [comment]
This is almost definitely not EnderTech's fault. The ID is -1 for the result of the recipe. The icon for the tank glass is wrong too.

Are you using a modpack?

**Comment by aik88** [comment]
yey self made modpack

**Comment by aik88** [comment]
Ok, my bad, the upload to server was incorrect.
Sry for eating ur time!
